### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by maujin111**
-Goal of the PR: Fix links

### CODE REVIEW

**Comment by felipemanga** [comment]
Are "Documentation" and "Tutorial" supposed to point to the same place? Might as well join them into a single link instead.

**Comment by maujin111** [comment]
Tutorials are supposed to be a section on the wiki, but it is still not create it, that is why point to the same place for now

**Comment by Zughy** [comment]
Why the `sheet.png` skin file has changed? I've compared it with the current version and apparently there is a new "t" icon in your PR file but it's not used anywhere

**Comment by maujin111** [comment]
> Why the `sheet.png` skin file has changed? I've compared it with the current version and apparently there is a new "t" icon in your PR file but it's not used anywhere

the "t" icon is for something else that i'm working on, it should not be problem

**Comment by maujin111** [comment]
@Zughy the sheet.png it's back to the original one

**Review by Zughy — APPROVED** [review]

**Pull request merged**
