### PR TITLE
Add build status to README

### PR DESCRIPTION
**Pull request by MintStudios**
The build status would provide a sense of confidence to people who want to compile the code.

A plus - It looks super nice.

### CODE REVIEW

**Comment by akien-mga** [comment]
Please use your own fork for changes instead of the upstream repository, so that we avoid having too many branches in the main repo that will be mirrored in all our forks.

Additionally, create a branch in this repo triggers a dedicated CI build, so we now have two CI builds in this PR.

**Comment by PerryHugh** [comment]
I think we should implement a policy of not merging broken code into master. This means that this svg will never change as master should **always** build correctly. That is kind of the point of master.

**Comment by MintStudios** [comment]
Yes, but it is always helpful to see that `build: passing` sign, even if it never changes. @PerryHugh sometimes bad code will get through. I know I can merge this now, but just to check, are you OK with this? (I want to delete this branch.)

**Comment by PerryHugh** [comment]
Go for it, if possible I feel it would look better being on the same line as either the title (LibreSprite) or the sub-section Compiling, centered right would be cool too. Don't know if that's possible though.

**Comment by MintStudios** [comment]
Yes, I would have to use in line html for that.

**Pull request merged**
