### PR TITLE
Remove aseprite related badges and start rebranding

### PR DESCRIPTION
**Pull request by JosefKuchar**
#10

### CODE REVIEW

**Comment by akien-mga** [comment]
The first commit is good, but I don't think we should start any rebranding yet. Giving this project a new name when it has no active maintainers or developers is pointless IMO. I prefer to give this privilege to whoever will decide to make something of it.

**Comment by akien-mga** [comment]
> but I don't think we should start any rebranding yet. Giving this project a new name when it has no active maintainers or developers is pointless IMO.

Well I see now that I did agree to the rebranding a couple of years ago: https://github.com/aseprite-gpl/aseprite-gpl/issues/8#issuecomment-253989087
I'm still not convinced it would bring anything meaningful without any team of developers ready to maintain it, but given the popular requests I guess I'll proceed with it.

I think I'll do it myself in one big commit though, there are still several instances of "Aseprite" even in the files you modified. And the renaming would warrant some explanations in the README, so better rewrite it.

**Comment by akien-mga** [comment]
I've merged the first commit as 12de9a16, thanks! I'll do the more exhaustive rebranding in a follow-up commit.

**Comment by JosefKuchar** [comment]
Ok, sure :)

**Pull request closed without merging**
