### PR TITLE
fix compile error

### PR DESCRIPTION
**Pull request by DublikuntMux**
## RP information

Fix copilation time error on linux with while comile with clang.

## How to test

Run copilation on linux with clang.

### CODE REVIEW

**Comment by maujin111** [comment]
Is there any issue associated to this PR

**Comment by DublikuntMux** [comment]
Yes
https://github.com/LibreSprite/LibreSprite/issues/399
https://github.com/LibreSprite/LibreSprite/issues/336

**Comment by maujin111** [comment]
Well everything works fine, thanks

**Review by maujin111 — APPROVED** [review]

**Comment by maujin111** [comment]
this PR should be re open

**Pull request merged**
