### PR TITLE
Prevent unicode text from interfering with shortcut input

### PR DESCRIPTION
**Pull request by felipemanga**
Should fix shortcuts like Ctrl+Shift+E.

### CODE REVIEW

**Comment by Zughy** [comment]
Still doesn't work here. Note: ctrl+shift+n works, I guess because there is no Shift+N shortcut

**Comment by felipemanga** [comment]
Can you try this? It works for me on PopOS:
```cpp
                  if (event.modifiers() & (she::kKeyCtrlModifier | she::kKeyCmdModifier)) {
                    SDL_StopTextInput(); // <-- add this line
                    break;
                  }
```

**Comment by Zughy** [comment]
@felipemanga seems to work flawlessly

**Review by Zughy — APPROVED** [review]
Works

**Pull request merged**
