### PR TITLE
Feat(Dark Mode)

### PR DESCRIPTION
**Pull request by RodrigoMedeirosRS**
Added a Dark Mode Theme, as optional skin.
What you think to make the dark theme as default skin, and change the current skin to light??? This will give us a new visual identity :)

### CODE REVIEW

**Comment by Ev1lbl0w** [comment]
This skin is basically a copy of [than's skin](https://github.com/tungkradle/aseprite-than/tree/master), you should at least mention that...

Also, from #55, @maujin111 implemented this [same theme](https://github.com/maujin111/than_dark_theme_libresprite) and is contacting the original author to see if he can port the theme to LibreSprite.

We could have an official "dark" theme for LibreSprite, but since there are like [10 of them](https://github.com/aseprite/themes), we should choose the one most people like.

**Comment by maujin111** [comment]
You placed it as an option to switch to dark mode or is it just a theme in the Skins section? 

I am currently working on the option to switch to dark mode or light mode with a check box in preferences and the auto-detection of the user theme of the operating system and based on that the program starts in dark mode or light mode.

I also haven't heard from the original author of the theme, it looks like she's been inactive since 2018.

**Comment by jjhaggar** [comment]
Since the license is [CC BY 4.0](https://github.com/tungkradle/aseprite-than/blob/master/LICENSE), even if we cannot contact her we could use her theme and give her appropriate credit and such (anyway we should continue trying to get in contact in deference to her). 

Oh, and I also love the idea of having dark theme as default :D 

I think it doesn't need to be exactly one of all the existent dark themes, maybe we could use  [than's skin](https://github.com/tungkradle/aseprite-than) as a base and tweak it a little so it gives LibreSprite a totallly new visual identity :)

**Comment by RodrigoMedeirosRS** [comment]
Yes i have based the Dark Theme on the Than's but is not only a single copy and paste, the than don't run directly on LibreSprite, and i have adapt serveral things to put it to work. The idea here is have a base, to produce our own color scheme.

**Comment by RodrigoMedeirosRS** [comment]
> You placed it as an option to switch to dark mode or is it just a theme in the Skins section?
> 
> I am currently working on the option to switch to dark mode or light mode with a check box in preferences and the auto-detection of the user theme of the operating system and based on that the program starts in dark mode or light mode.
> 
> I also haven't heard from the original author of the theme, it looks like she's been inactive since 2018.

Sorry, i only put the theme on skin section

**Comment by PerryHugh** [comment]
I don't think the dark theme should be default. Our default theme is the more unique aesthetic of LibreSprite, a dark theme is reminiscent of thousands of other applications. Dark themes are a great optional feature for people who work in really low light environments as eye strain is softened with high contrast characters, but besides that I see no appeal or personality to them.

I think our default theme should represent the personality of LibreSprite, exciting and easy to learn for both kids and adults. Pixel art is fun, not drab!

**Comment by TheEA66** [comment]
Where can I get the theme?

**Comment by maujin111** [comment]
@TheEA66 here:  https://github.com/maujin111/than_dark_theme_libresprite

**Review by PerryHugh — CHANGES_REQUESTED** [review]
if you would be down to make this an optional theme selection instead of the default, and add attribution in the appropriate places so we are correctly abiding by the terms of CC-BY 4.0, I would love to merge.

**Pull request closed without merging**
