### PR TITLE
Remove licenses

### PR DESCRIPTION
**Pull request by nanoslayer**
Remove the licenses in docs/licenses as they aren't needed (and some are even outdated).

### CODE REVIEW

**Comment by Zughy** [comment]
As discussed in #141 , this is extremely risky. Are you sure no license file is needed?

**Comment by nanoslayer** [comment]
This should be fine. The licenses are for external libraries and can be safely removed.

**Comment by felipemanga** [comment]
The fact that a library is "external" does not imply that you can simply remove the license.
- Jinete: probably a precursor to the Aseprite UI Library. Should be safe to remove.
- FTL (FreeType): Still in use, license is required in final binary.
- GPL / LGPL: I assume this is LibreSprite's. Should keep these.
- MIT: I have no idea what code this is from. Delete?
- ZLIB: Safe to remove since it's only required for a source distribution.
- allegro4: "it would be nice if you mentioned Allegro somewhere in the credits, but you are not required to do this. We trust you not to abuse our generosity." Might as well keep it.
- curl: Looks like curl is no-longer being used. Should be safe to remove.
- giflib: Still in use, license is required in final binary.
- gtest: Still in use, license is required in final binary.
- libjpeg: Still in use, license is required in final binary.
- libpng: "acknowledgment is not required but would be appreciated."
- xfree86: Still in use,  license is required in final binary.

**Comment by nanoslayer** [comment]
>     * GPL / LGPL: I assume this is LibreSprite's. Should keep these.

These are not LibreSprite's licenses. Those are LICENSE.txt, src/base/LICENSE.txt, src/cfg/LICENSE.txt, etc. So they can be removed.

>     * allegro4: "it would be nice if you mentioned Allegro somewhere in the credits, but you are not required to do this. We trust you not to abuse our generosity." Might as well keep it.

Perhaps we should move the allegro license to src/allegro/LICENSE.txt, since its source code is present.

>     * FTL (FreeType): Still in use, license is required in final binary.
>     * giflib: Still in use, license is required in final binary.
>     * gtest: Still in use, license is required in final binary.
>     * libjpeg: Still in use, license is required in final binary.
>     * libpng: "acknowledgment is not required but would be appreciated."
>     * xfree86: Still in use,  license is required in final binary.

I'm not sure we really need to keep these licenses in the repository. It's probably enough to link to the project's homepage.

**Comment by Zughy** [comment]
> I'm not sure we really need to keep these licenses in the repository. It's probably enough to link to each project's website.

Actually, I'm not even sure you have to name them if their just external libraries. Either way, this is already done in `CONTRIBUTORS.md`

>     * MIT: I have no idea what code this is from. Delete?

Some classes inside LibreSprite are MIT, I don't know if they count

MIT and Allegro4 aside, they should be all safe to remove

I've also noticed you've removed the `files` folder, putting everything in `docs`. I feel it's pretty messy, please revert that change

**Comment by nanoslayer** [comment]
> Some classes inside LibreSprite are MIT, I don't know if they count
> 
> MIT and Allegro4 aside, they should be all safe to remove

The MIT classes each have their own LICENSE.txt in src/, so they aren't needed either.

> I've also noticed you've removed the `files` folder, putting everything in `docs`. I feel it's pretty messy, please revert that change

Done.

**Comment by Zughy** [comment]
Please edit `CONTRIBUTORS.md` too (https://github.com/LibreSprite/LibreSprite/blob/master/CONTRIBUTORS.md), as right now licenses point to dead links.

I'd remove the link and use a format like

[gtest](https://github.com/google/googletest) - BSD-3
[XFree86](http://www.x.org/) - MIT

etc.

**Comment by nanoslayer** [comment]
> Please edit `CONTRIBUTORS.md` too (https://github.com/LibreSprite/LibreSprite/blob/master/CONTRIBUTORS.md), as right now licenses point to dead links.

Done.

**Comment by Zughy** [comment]
Ok, so: after talking with @felipemanga on Matrix/Discord, we actually need those licenses for the binary. I still like the CONTRIBUTORS.md list clean-up, and Jinete is definitely useless, so feel free to open another PR with these changes only

**Pull request closed without merging**
