### PR TITLE
Added support for Snap packaging

### PR DESCRIPTION
**Pull request by simos**
Snap packages are a way to create an installation package of an application.

With this pull request, I add the necessary configuration to create a snap package for LibreSprite.

I have already created and published a test package for LibreSprite, called `libresprite-simosx`.
You can install with `sudo snap install libresprite-simosx`. Then, run as `libresprite-simosx.libresprite`.

To create an official snap package yourselves and upload to the Snap Store, you just need to:
1. Install the `snapcraft` creation tool with `sudo snap install snapcraft --classic`.
2. In the directory of LibreSprite, run `snapcraft`. This will take some time, and will produce a *.snap package in the same directory.
3. Then, see at https://docs.snapcraft.io/build-snaps/publish on how to publish to the Store.

Alternatively, you can make use of the snap build servers at https://build.snapcraft.io/
Here, you just post the Github URL of the project, and automatically the build servers will build snap packages for you. You still need to visit https://dashboard.snapcraft.io/ to manage the final stages of the release.

Once you register `libresprite` on the Snap Store and release the snap package, tell me so that I remove my test `libresprite-simosx` snap package from the Snap Store.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Do you know if this packaging works?

**Comment by simos** [comment]
Here is a screenshot of the app running from the snap package,
https://i.imgur.com/E3OFDOO.png

I have put `strict` confinement for the application, and did not enable networking for the application.
If the application requires networking, it is easy to enable and tell me so.

I have tested on Ubuntu 16.04, though I believe it should work with any distribution per https://docs.snapcraft.io/core/install

**Comment by akien-mga** [comment]
Awesome, looks great!

Does the folder have to be at the root of the repo, or could it go in `desktop/snap/`? Most other distribution-related stuff is in `desktop/` currently.

**Comment by simos** [comment]
There are three locations for the `snapcraft.yaml` configuration file so that it gets automatically found by the `snapcraft` tool. These are:

1. snap/snapcraft.yaml (as it is now)
1. .snapcraft.yaml (as a hidden file)
1. snapcraft.yaml (as a file in the root directory of the package)

If any of these is fine, tell me and I can make the change.

As far as I know, if the `snapcraft.yaml` is placed in another directory (`desktop/`), then a user would need to copy it manually before running `snapcraft`, and the build servers at https://build.snapcraft.io/ will not be able to find it when creating automatically a snap package for you.

**Comment by akien-mga** [comment]
`.snapcraft.yaml` would be fine to me, but then I guess you would have no location to put the `libresprite.desktop` file? If so I think we can go with `snap/` for now and change later on if need be.

Unless the `.snapcraft.yml` can reference the pre-existing `desktop/libresprite.desktop` and thus remove the need for `snap/libresprite.desktop`?

BTW you can set the version to `1.0-git` or `1.0-dev`, I'm about to push a commit that sets it to this value.

**Comment by Conan-Kudo** [comment]
It should be possible to reuse the existing `libresprite.desktop` file, if by no other means than by using a symlink.

**Comment by simos** [comment]
I moved the configuration file to be a hidden file `.snapcraft.yaml`.

I changed the version to `1.0+git` (I used the plus sign as it is common with snaps. You may switch to `-` if you want to.).

I fixed the issue with the .desktop file, now snapcraft will be able to reuse the existing one.

**Comment by maujin111** [comment]
i use this snap on Arch, but don't show any launcher on the menu launcher. i have to navigate to /snap/libresprite-simosx/2/bin/aseprite to launch it

**Review by PerryHugh — APPROVED** [review]
Looks good, someone should register it to the app center like you suggest. Thank you for laying the groundwork.

**Pull request merged**
