### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by nanoslayer**
Remove the Steam API, webserver, automatic updater, news listbox, and trial version. This also removes a dependency on curl.

Also use shared libraries where possible.

### CODE REVIEW

**Comment by nanoslayer** [comment]
For some reason I can't get these changes to build successfully on Travis CI (it failed with a segmentation fault). Since Travis CI will be shutting down soon anyways, I propose we move to an alternative. I would recommend using [sourcehut builds](https://sourcehut.org). They support various Linux distributions and BSDs. I can help set this up if anyone is interested.

Here is a successful build of my LibreSprite repository for Debian on sourcehut builds: https://builds.sr.ht/~adnano/job/452781
And here is the build manifest that accomplished that: https://builds.sr.ht/api/jobs/452781/manifest
I can also make build manifests for other Linux distributions.

**Review by PerryHugh — APPROVED** [review]
Damn this is sweet, thank you!

Travis was way beyond my normal scope of coding and I remember spending a lot of time learning it to set it up for this repo, so I probably messed something up in config. It's been a long time since then so it's all out of my head at this point. If you are capable of making the transition away from travis that would be the tops.

**Comment by maujin111** [comment]
@PerryHugh seems this PR causes a failure in compile time  #137

**Comment by nanoslayer** [comment]
Glad this was finally merged! I had almost given up hope :P

**Comment by nanoslayer** [comment]
> Travis was way beyond my normal scope of coding and I remember spending a lot of time learning it to set it up for this repo, so I probably messed something up in config. It's been a long time since then so it's all out of my head at this point. If you are capable of making the transition away from travis that would be the tops.

I would be willing to help with the transition to sourcehut builds. Unfortunately, sourcehut builds is no longer available free of charge due to abuse by cryptocurrency miners, but we may be able to get an exception as an open source project.

**Comment by maujin111** [comment]
@PerryHugh  I tried several times to compile installing various libraries, and it doesn't work. I Suggest revert the merge until is properly fix

**Comment by PerryHugh** [comment]
@nanoslayer any clue why @maujin111 isn't able to build?

**Comment by maujin111** [comment]
@PerryHugh Installing the new dependencies and updating the install.md file is now possible to compile it. But I didn't try to compile it on Windows yet

**Comment by nanoslayer** [comment]
@maujin111 You'll have to install the following dependencies in order to compile on Windows:

* freetype: https://www.freetype.org
* giflib: http://giflib.sourceforge.net
* gtest: https://github.com/google/googletest
* libjpeg-turbo: https://www.libjpeg-turbo.org
* libpng: http://www.libpng.org
* libwebp - https://developers.google.com/speed/webp
* pixman: http://www.pixman.org
* tinyxml: http://www.grinninglizard.com/tinyxml
* zlib: https://www.zlib.net

**Comment by maujin111** [comment]
But why?, those dependencies already are in the project. Add more steps for compile, just mess up things

**Comment by nanoslayer** [comment]
The motivation for unbundling the libraries was layed out in #5.

I'll investigate to see if there is a way to make compilation on Windows easier.

**Comment by Zughy** [comment]
@nanoslayer yes there is. You can choose between vcpkg and conan. According to https://www.reddit.com/r/cpp/comments/9m4l0p/conan_vcpkg_or_build2/ Conan is more complete. To see a project using vcpkg, have a look at Minetest's readme https://github.com/minetest/minetest

Anyway, I'm having a look myself as I'm planning to test it tomorrow on Windows

**Pull request merged**
