### PR TITLE
Move icons to proper directory

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by PerryHugh** [comment]
Do all references to these files need to be updated too?

**Comment by Alexander-Wilms** [comment]
No, since the whole directory gets copied: https://github.com/LibreSprite/LibreSprite/blob/master/desktop/CMakeLists.txt#L14

I tested it and didn't see any missing icons.

**Comment by maujin111** [comment]
I will review this tomorrow

**Comment by nanoslayer** [comment]
This seems correct. See the [Icon theme specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout).

**Review by maujin111 — APPROVED** [review]

**Pull request merged**
