### PR TITLE
Add Spanish documentation

### PR DESCRIPTION
**Pull request by maujin111**
- added readme_es
- added license_es 
- added contributing_es 
- added install_es 
- added code_of_conduct_es
- updated code_of_conduct.md to v2.0 (latest)
- updated links to spanish documentation

### CODE REVIEW

**Comment by MintStudios** [comment]
I think that someone who knows Spanish should look this over. I think that @jjhaggar does. Could you look this over?

**Comment by akien-mga** [comment]
I appreciate the effort, but I don't think it is useful to have Spanish documentation for contributors. The application itself is in English, the codebase is in English, and communication between contributors is in English.

Duplicating all doc files in this repo to possibly dozens of languages sounds like a bad idea, and they will inevitably end up with outdated documentation.

**Comment by maujin111** [comment]
At least it could be placed in a separate folder. 
I know that all developers and those who want to contribute should know how to speak English. But there are people who aren't lucky enough to talk about it so fluently. For example, the steps are very well explained in the contribution document, but it would be nice for someone who doesn't have as much knowledge of the language to understand how to make their contribution no matter how small Or better understand the steps to perform the build.

**Comment by jjhaggar** [comment]
Since my mother language is Spanish I feel a bit divided about this, but I think @akien-mga is right, this could easily end up with outdated docs.

On the other hand, I have taken a look at the Spanish docs and they seem good to me (just in case they are added anyways).

**Comment by Ev1lbl0w** [comment]
I agree: this would quickly clutter the repository with `README.md`s, `CONTRIBUTING.md`s, etc... when a potential developer very likely knows the bases of English.

What can and should be localized is the program itself. But like I said on #49, for that to happen we need to implement a system first.

**Comment by maujin111** [comment]
So we all agree, should i close this request?

**Comment by MintStudios** [comment]
Yes, you should close this.

**Pull request closed without merging**
