### PR TITLE
Default canvas size shortcut on C

### PR DESCRIPTION
**Pull request by Zughy**
Hello, first PR here. I use ASEprite every day to work and I'm super glad to have found a free software fork :)
Long story short, a few (to me) essential things are missing, so I've decided starting with the most basic one: the "C" shortcut for resizing the canvas. I hope it's fine!

### CODE REVIEW

**Comment by Zughy** [comment]
so uhm.. it's been more than 5 months for adding a shortcut, and in general I notice there are basically no new commits. Is this fork dead?

**Comment by jjhaggar** [comment]
> 
> 
> so uhm.. it's been more than 5 months for adding a shortcut, and in general I notice there are basically no new commits. Is this fork dead?

It's not dead but it probably would need more help. I think that there is only one active mantainer at the moment (maujin111). 

If you can continue helping developing LibreSprite with more features & pull requests all community would be grateful :) I'd love to help too, but I'm afraid I'm more of a pixel artist ^^U

**Comment by Zughy** [comment]
> If you can continue helping developing LibreSprite with more features & pull requests all community would be grateful :)

I'd love to as I do pixel art for a living and I'd like to support free software, the problem is that if I don't see any activity in here I fear I might end up just wasting time (my C++ knowledge is nowhere near to allow me to handle a fork on my own)

**Comment by jjhaggar** [comment]
> 
> I'd love to as I do pixel art for a living and I'd like to support free software, the problem is that if I don't see any activity in here I fear I might end up just wasting time (my C++ knowledge is nowhere near the level that allows me to handle a fork on my own)

The Discord server is a bit more active than here, this is the link in case you want to join: https://discord.gg/95gbyU5

**Comment by Zughy** [comment]
Thank you for the invitation but I don't have Discord and I'd really like avoid creating it again, especially to work on something which is FOSS. I guess I'll just wait

**Pull request merged**
