### PR TITLE
Add sourcehut build manifests

### PR DESCRIPTION
**Pull request by nanoslayer**
As discussed in #102.

I can help set up integration with sourcehut builds, but I'll likely need access to the repository.

### CODE REVIEW

**Review by maujin111 — APPROVED** [review]

**Comment by Zughy** [comment]
Didn't we want to use GitHub Actions instead of Travis?

**Comment by nanoslayer** [comment]
GitHub actions is another option, though I am not too familiar with it.

**Comment by Zughy** [comment]
No, sure, I was asking as I've seen Maujin approval when he was the one proposing GitHub Actions

**Comment by nanoslayer** [comment]
See the [documentation](https://man.sr.ht/dispatch.sr.ht/github.md) for connecting builds.sr.ht to GitHub.

I can help set this up if needed.

**Comment by Zughy** [comment]
This must be done by @maujin111 , as not even I have enough permissions to edit those settings

**Pull request merged**
